version: "3"

services:
  postgres:
    container_name: postgres 
    image: postgres:15.2-alpine
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: